# Silver Layer Model Configuration

version: 2

models:
  - name: silver_customers
    description: Cleansed and standardized customer data
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      
      - name: email
        description: Standardized email (lowercase, trimmed)
        tests:
          - not_null
      
      - name: phone_clean
        description: Phone number with only digits
      
      - name: state
        description: State code (uppercase)
      
      - name: country
        description: Country code (uppercase)
      
      - name: dbt_updated_at
        description: Timestamp when record was last processed by dbt
  
  - name: silver_orders
    description: Cleansed order data with validation
    columns:
      - name: order_id
        description: Unique order identifier
        tests:
          - unique
          - not_null
      
      - name: customer_id
        description: Reference to customer
        tests:
          - not_null
          - relationships:
              to: ref('silver_customers')
              field: customer_id
      
      - name: order_date
        description: Date order was placed
        tests:
          - not_null
      
      - name: order_status
        description: Current order status
        tests:
          - accepted_values:
              values: ['PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
      
      - name: total_amount
        description: Total order amount (validated >= 0)
